### ISSUE TITLE
Failure on the latest ZMQ library

### ISSUE THREAD

**Issue by snunez1** [yitzchak/common-lisp-jupyter#106]
I recently upgraded my MSYS2 installation, and it includes zeromq 4.3.4-2.  Common-lisp-jupyter now fails with the error below:

![sbcl-libzmq-error](https://github.com/yitzchak/common-lisp-jupyter/assets/7775472/425c709f-c731-4f6d-8ba4-ebf6dee45784)

This doesn't happen if I load at the REPL, only when loading with JupyterLab.

OS: Windows 10, latest update
SBCL: 2.1.6

Any ideas?  I seem to recall this happening before due to some changes in the underlying zmq library.

**Comment by snunez1** [comment]
@yitzchak, can you confirm this works with the latest zmq?  I've reinstalled everything from scratch using the [Miniconda installation instructions](https://github.com/yitzchak/common-lisp-jupyter/wiki/Windows-Installation) for MS Windows and it's still not working:

```
; Loading "common-lisp-jupyter"
...Unhandled LOAD-FOREIGN-LIBRARY-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {101C540003}>: Unable to load foreign library (LIBZMQ).
  Error opening shared object "libzmq.dll":
 The specified procedure could not be found.

```

**Comment by snunez1** [comment]
Confirming the problem still exists in the latest SBCL, version 2.3.8.

**Comment by snunez1** [comment]
Hello, anyone home?

**Comment by yitzchak** [comment]
Everything works fine with the same versions on Arch, so this looks like a Windows/MSYS specific issue. I don't have a Windows machine so I'll fine some time to have to setup a VM to replicate.

**Comment by snunez1** [comment]
Anything discovered?  I noticed a new docker issue reported on stackoverflow; not sure if it's related.

**Comment by snunez1** [comment]
Is there something I can do to help here?

**Comment by yitzchak** [comment]
I have not been able to replicate this yet.

**Comment by yitzchak** [comment]
I did use the JupyterLab that part of msys2, so it could be a conflict between miniconda and msys2.

**Comment by snunez1** [comment]
OK, closing because it works if `jupyter-lab` is invoked from MSYS2 MING64 shell, but not if invoked from PowerShell.  Finally, for anyone finding this in future, jupyter-lab is the one installed from *windows* miniconda, not from MSYS.

I wonder if a self-contained installer would be helpful here?
