### ISSUE TITLE
PATH passed to launch_kernel/Popen() doesn't contain ~/roswell/bin

### ISSUE THREAD

**Issue by ayjayt** [yitzchak/common-lisp-jupyter#112]
I followed the installation instructions...

So I deleted my original issue, but it's still in the same way: If we're using jupyter hub, we need a way to do per-user path, and that seems hard with the defaults. The lab's inherit their PATH from the hub, which is root. Looking for ways to do it in the config, but then this would be good to add to the docs.

**Comment by ayjayt** [comment]
ax that, /etc/environment is loaded by the server launcher.

This is probably cause I'm using hun on system d but I'm gonna suss out a solution right now anyway.

**Comment by ayjayt** [comment]
**SOLUTION** (hack)
Not great,

I changed `c.Spawn.cmd` in `jupyterhub.config` (or whatever it's called) to `jupyterhub-singleuser` to `jupyterhub-singleuser-alias` and created said `jupyterhub-singleuser-alias` as a bash script in the same directory as the `jupyterhub-singleuser`:

```
export PATH=$PATH:$HOME/.roswell/bin
exec jupyterhub-singleuser
```
Didn't find any other way to do. Could be wrong. There is no other script that gets sourced before the server is started that allows you to export per user variables. Nothing seems to be executed in a shell by default.

**Comment by yitzchak** [comment]
I'm not quite sure why is this a common-lisp-jupyter issue. I don't really use Roswell anymore, but there is an "env" section in the kernel file. https://jupyter-client.readthedocs.io/en/latest/kernels.html#kernel-specs

**Comment by ayjayt** [comment]
Thanks, I posted here because I followed the instructions here to install it all and still came across the error.

What should we use if not ROS?

That 'env' variable in the kernel file might work, but if we were going to include a note about that in the instructions to make them compatible with jupyterhub, where would it be, and where we would find the kernel?

**Comment by yitzchak** [comment]
You can find the kernel files by doing `jupyter-kernelspec list`

**Comment by ayjayt** [comment]
Ok, so I'll test it out... would you be open to a pull request to add to
the docs this information during installation so jupyter hub users can also
common-lisp-jupyter with roswell? or should i not bother

**Comment by yitzchak** [comment]
Sounds good
