### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [yitzchak/common-lisp-jupyter#125]
Building with SBCL 2.4.6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 3a69118995360471dcada96c5d6edc69138477d1

*common-lisp-jupyter* fails to build with the following error:

```
Unhandled SB-PCL::FIND-METHOD-LENGTH-MISMATCH in thread #<SB-THREAD:THREAD tid=3516053 "main thread" RUNNING {1000DC8003}>: The generic function #<STANDARD-GENERIC-FUNCTION ECLECTOR.PARSE-RESULT:MAKE-SKIPPED-INPUT-RESULT (1)> takes 5 required arguments; was asked to find a method with specializers (MY-CLIENT T T T)

```

[Full log here](http://report.quicklisp.org/2024-07-24/failure-report/common-lisp-jupyter.html)

**Comment by yitzchak** [comment]
This should be fixed
