### ISSUE TITLE
A Jupyter widget

### ISSUE THREAD

**Issue by justjoheinz** [yitzchak/common-lisp-jupyter#126]
I am unable to make widgets appear. I  just get "A jupyter widget'" as text. Actually the same behavior occurs in the sample pages, e.g. https://nbviewer.org/github/yitzchak/common-lisp-jupyter/blob/master/examples/widgets.ipynb

I am a bit at a loss where I have to start looking.

**Comment by yitzchak** [comment]
That is usually an indicator that you are missing the front-end code for widgets. If you run `jupyter-labextension list` in shell you should see `@jupyter-widgets/jupyterlab-manager` listed. If it isn't you can install it via `jupyter-labextension install @jupyter-widgets/jupyterlab-manager`. You can also do this via the extension manager in the the JupyterLab interface.

**Comment by justjoheinz** [comment]
@yitzchak - Thanks a lot - this solved the problem indeed. Maybe add it to a trouble shooting section in your very good installation instructions for common-lisp-jupyter?
