### ISSUE TITLE
Kernel Startup Failure on Windows and SBCL 1.4.2

### ISSUE THREAD

**Issue by WetHat** [yitzchak/common-lisp-jupyter#33]
Hi yitzchak,

I'm getting an exception on attempting to start the common lisp kernel on windows:

~~~ Lisp
To load "common-lisp-jupyter":
  Load 1 ASDF system:
    common-lisp-jupyter
; Loading "common-lisp-jupyter"
..........
[kernel] Connection file = C:UsersPeterAppDataRoamingjupyterruntimekernel-bcc11bbc-78d1-417c-9804-4896bb42025a.json

debugger invoked on a SB-INT:SIMPLE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10027900C3}>:
  error opening #P"C:/PortableApps/MaximaPortable/App/Maxima/bin/UsersPeterAppDataRoamingjupyterruntimekernel-bcc11bbc-7
8d1-417c-9804-4896bb42025a.json":
    The system cannot find the file specified.
~~~

As you can see the path to the connection file is missing the backslashes. I do not know much about jupyter kernels, but I tend to believe this is caused by jupyter passing the path to the connection file into the Lisp kernel as a string with **single backslashes**. Lisp strings, however, require **double backslashes** to represent a single backslash. Hence this is an issue which affects Windows systems only.

Since I do not know how anything about the Jupiter kernel interfaces, I came up with this dirty hack:

In `kernel.lisp`, function `run-kernel`, I've added this form at the top:

~~~ Lisp

(defun run-kernel (kernel-class connection-file-name)
  "Run a kernel based on a kernel class and a connection file."
  
  (let ( ; WetHat: Hack do work around single back-slashes in connection-file-name
           (json (subseq connection-file-name (search "kernel" connection-file-name)))
           (appdata (substitute-if #\/ (lambda (c) (eq c #\\)) (sb-unix::posix-getenv "APPDATA")))
         )
      (setq connection-file-name (concatenate 'string appdata "/jupyter/runtime/" json))
   )
  …
)
~~~
 
That makes it work. I think is a temporary work around until a proper fix is found.

Regards,

WetHat

**Comment by yitzchak** [comment]
Thanks for reporting the issue! I'll look into it.

**Comment by yitzchak** [comment]
I think I may have a fix with #34 if you want to try it out. 

The obvious solution would be to pass the connection file path as an actual command line argument outside of a Lisp string, but some Lisp implementations (ECL for one) don't appear to support this. Instead I introduced a raw string format to the reader. I'm not crazy about this method, but I haven't come up with anything else yet.

**Comment by WetHat** [comment]
Hi yitzchak,

The reader-macro approach in #34 works. I've applied the changes to `cl-kernel.lisp` and `utils.lisp`, ran
`(cl-jupyter:install)` again to update `kernel.json`. After that the common-lisp-jupyter kernel starts up and runs just fine. I think you can pull #34 in to the master branch.

Your support is very much appreciated!

WetHat

**Comment by yitzchak** [comment]
Awesome. Thanks for helping out!
