### ISSUE TITLE
support jupyterlab

### ISSUE THREAD

**Issue by andreasplesch** [yitzchak/common-lisp-jupyter#37]
Jupyterlab would be great.

I took a stab at it here:

https://mybinder.org/v2/gh/andreasplesch/common-lisp-jupyter/dockerstack?urlpath=lab/

by starting from the minimal Dockerfile from https://github.com/jupyter/docker-stacks

It uses Ubuntu Bionic, so it took figuring out the differences to Arch but it seems to work now from my dockerstack branch:

https://github.com/andreasplesch/common-lisp-jupyter/blob/dockerstack/Dockerfile

If there is interest, I can PR, perhaps to a branch here.

**Comment by yitzchak** [comment]
I am interested, but I would really prefer to use Arch unless there is an obstacle there. I have had a lot of bad experiences with Ubuntu having broken and outdated packages.

**Comment by andreasplesch** [comment]
https://github.com/andreasplesch/common-lisp-jupyter/blob/jupyterlab/Dockerfile

was my initial attempt starting with Arch. This became complicated and so I explored the official Jupyter docker stacks which for some reason use Ubuntu.

The Jupyter docker images have the desirable property that they are maintained and essentially guaranteed to work with Jupyter and Jupyterlab.

A bonus is also that Roswell maintains a .deb Debian package indicating their support for Debian/Ubuntu.

The hardest part was to collect the 32bit libraries and headers for cmucl. Arch may have more builtin 32bit support.

It may make sense to actually just focus on sbcl and ccl kernels in a dedicated docker image avoiding 32bit or java issues.

I mainly am interested in trying gendl on Jupyterlab.

**Comment by andreasplesch** [comment]
Just a quick note that I added lab widget installation to

https://mybinder.org/v2/gh/andreasplesch/common-lisp-jupyter/dockerstack?urlpath=lab/

This means that the example widget notebooks work now. But they require an initial restarting of the kernel after loading for the widgets to show up, from the interface. Not sure why. Possibly a lab issue.

**Comment by yitzchak** [comment]
Ok. I am looking into the mechanism of how Binder actually chooses JupyterLab. It's not immediately obvious by the Arch kernel doesn't work since it works offline.

**Comment by andreasplesch** [comment]
It is difficult to work out how Binderhub works in detail. My understanding it uses Kubernetes to make and launch servers somewhere which then use Docker to run an image. repo2docker is used to generate docker images, from configuration files or from Dockerfile specs.

To me the most understandable way to follow what seems to be happening is to look at the docker setups in https://github.com/jupyter/docker-stacks which I think you have done.

https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile

is the starting point. It sets up the base system and uses conda to install jupyter. It may be safest to just follow along and also use conda with Arch although it is unclear why it should be necessary to use multiple package systems.

The start scripts are copied to /usr/local/bin . I am not sure if Mybinder.org and the default Binderhub configuration would expect them there or just somewhere in the PATH.

Binder chooses which interface to use (classic or lab) from supplied configuration files or from the URL. I think it is actually Jupyter which chooses. In my mind Binder just connects a Jupyter instance to a server and runs it.

**Comment by yitzchak** [comment]
I think I got it working at [here](https://mybinder.org/v2/gh/yitzchak/common-lisp-jupyter/add-jupyter-lab-2?urlpath=lab)

It doesn't appear to need jupyterhub installed so I will probably work on a separate branch in order to clean up the image.  The key line was `jupyter serverextension enable --py jupyterlab --sys-prefix` which enables the JupyterLab extension from the `jupyter-notebook` command line.

**Comment by andreasplesch** [comment]
Great. Yeah, not sure why the jupyter docker stack images have jupyterhub.  It may be for historic reasons/older setups. https://github.com/jupyterlab/jupyterlab/pull/2222 seems to apply.

The CMD Dockerfile directive, I believe, is used together with ENTRYPOINT. There may be a default entrypoint on binder which uses the CMD argument. Not sure what tini is exactly for.

The different start scripts are for different situations, eg. when used in some setup other than mybinder.org.

**Comment by andreasplesch** [comment]
One difference of using conda is that it installs packages in a user writable location while pacman, of course, does not. For jupyter and jupyter lab that seems to be the standard approach, letting than users install lab extensions and things

**Comment by yitzchak** [comment]
BinderHub appears to ignore CMD and ENTRYPOINT. It always calls jupyter-notebook which is why adding the jupyterlab server extension is required.

Current version is [here](https://mybinder.org/v2/gh/yitzchak/common-lisp-jupyter/add-jupyter-lab-3?urlpath=lab) with mostly working widgets.

**Comment by andreasplesch** [comment]
I had noticed that the first invocation of make-widget returns with an error but then all subsequent ones are successful. So something is exercised the first time.

**Comment by yitzchak** [comment]
I've managed get the extension manager to work by doing a user based install.

I am seeing the same thing regarding the widgets.

**Comment by yitzchak** [comment]
I've reproduced the widget problem outside of Docker in regular JupyterLab. The problem does not appear in Jupyter Notebook. At this point I will probably open a separate issue for this problem and merge #39 as is.
