### ISSUE TITLE
First JupyterLab widget does not render

### ISSUE THREAD

**Issue by yitzchak** [yitzchak/common-lisp-jupyter#40]
The first attempt to display a widget fails in JupyterLab with `Model not found.` Jupyter Notebook seems fine.

**Comment by yitzchak** [comment]
@andreasplesch The widget version numbers for JupyterLab have been updated. Opening a notebook with old widgets already instantiated appears to cause the first newly created widget to fail upon displaying. Possible fix [here](https://mybinder.org/v2/gh/yitzchak/common-lisp-jupyter/fix-jupyter-lab-widgets?urlpath=lab)

**Comment by yitzchak** [comment]
@andreasplesch I think this is fixed in master. Can you give it a try? Seems to require clearing all output first.

**Comment by andreasplesch** [comment]
I tried both
https://mybinder.org/v2/gh/yitzchak/common-lisp-jupyter/master?urlpath=lab
and
https://mybinder.org/v2/gh/andreasplesch/common-lisp-jupyter/docker-stack?urlpath=lab

In both widgets work fine now, with and without clearing all outputs first. There was one exception with running all cells without clearing all output with the julia example but I could not reproduce it.

**Comment by yitzchak** [comment]
I forgot to reset the julia example. Should be fixed now.

Also, please note that I just removed `make-widget` in lieu of `make-instance`.

Unless you have got an objection I am going to close these two issues. Seems like they are resolved.

**Comment by andreasplesch** [comment]
No objection at all to closing these.

**Comment by yitzchak** [comment]
@andreasplesch Awesome. Thanks for the help!
