### ISSUE TITLE
Make cl-jupyter:install QL detection smarter

### ISSUE THREAD

**Issue by Ambrevar** [yitzchak/common-lisp-jupyter#61]
Currently, calling `(cl-jupyter:install)` generates a kernel that calls onto Quicklisp (with `ql:quickload`).  This breaks the kernel for people not using Quicklisp (like those of us who use Guix as their CL package manager).

To force the use of `asdf:load-system` instead, one must currently pass `:system t` to `cl-jupyter:install`.

What about calling `(find-package :quicklisp)` to check for quicklisp presence instead?  This way, the `install` function would automatically know whether to use quicklisp of not. 

I also suggest documenting this option in the tutorial :)

**Comment by yitzchak** [comment]
Thanks for the suggestion. I'll look into it.

**Comment by Ambrevar** [comment]
Excellent, thanks!
