### ISSUE TITLE
Installation on Linux without Roswell

### ISSUE THREAD

**Issue by kolloid** [yitzchak/common-lisp-jupyter#7]
Hello,
I have a Linux Mint with sbcl and python already installed. No Roswell. How can I install common-lisp-jupyter in my equipment?
Thanks
Tom

**Comment by yitzchak** [comment]
You would have to clone the repo and manually install a kernel.json file for Jupyter. If you really want to do that then you should clone the repo into Quicklisp's `local-projects` directory and create a `~/.local/share/jupyter/kernels/common-lisp/kernel.json` with the following

```json
{
  "argv": [
    "sbcl", 
    "--eval",
    "(ql:quickload :common-lisp-jupyter) (jupyter:run-kernel 'common-lisp-jupyter:kernel \"{connection_file}\")"
  ],
  "display_name": "Common Lisp",
  "language": "common-lisp"
}
```

I would encourage you to try Roswell, though. It will do all of this automatically and it will not interfere with your local SBCL installation. Plus you can switch implementations by using `ros use ccl-bin`.

**Comment by kolloid** [comment]
Thanks, I will try to install it manually, following your instructions.

As for Roswell, I don't see the need for it, frankly. I use only
sbcl/slime, and quicklisp as package manager.
Tom

**Comment by ryukinix** [comment]
I still think that the more easy way it's just use docker. Like this:
```
docker run  --network=host -it neowaylabs/common-lisp-jupyter jupyter notebook --ip=127.0.0.1
```

**Comment by yitzchak** [comment]
@kolloid I've add a function to aid with installation for those that do not want to use Roswell. After you have cloned the repo into Quicklisp's `local-projects` directory then evaluate the following in SBCL.

```lisp
(ql:quickload :common-lisp-jupyter)
(cl-jupyter:install)
```

Once this package is in the Quicklisp distribution then cloning into `local-projects` won't be needed.

**Comment by kolloid** [comment]
Sorry, spent a few days out of town and disconnected.
Tarn, I just tried the new installing procedure that you created and it
works. The other script that you sent left something undeclared and it
didn't work but now all is ok.
Thanks
Tom

**Comment by yitzchak** [comment]
Awesome! Glad it's working, Tom.
