### ISSUE TITLE
Render in github/gitlab?

### ISSUE THREAD

**Issue by Symbolics** [yitzchak/common-lisp-jupyter#70]
I've started publishing notebooks to github, and noticed they don't render they way most other notebooks do. The most likely explanation is that they don't run a common-lisp-jupyter backend. So, two questions:

1. Is there a way to save a notebook such that it would render on github?
2. Is there an alternative repo, say gitlab.common-lisp.net that would have a common-lisp kernel?

It would be nice to be able to show off some of the data-science work without forcing the user to setup an environment, checkout the notebook and run it.

**Comment by yitzchak** [comment]
Can you give me an example notebook?

**Comment by Symbolics** [comment]
https://github.com/Lisp-Stat/IPS/blob/master/notebooks/Chapter-1/Categorical.ipynb

**Comment by yitzchak** [comment]
Not sure what you mean, I se the graphs and the outputs fine. What specifically is rendering differently?

**Comment by Symbolics** [comment]
Opps. It turns out to be my overly aggressive JavaScript blocker. There are two additional sites required for plots to render.

**Comment by yitzchak** [comment]
Awesome. Glad you got it solved.
