### ISSUE TITLE
Swap ( and [ keys

### ISSUE THREAD

**Issue by Symbolics** [yitzchak/common-lisp-jupyter#73]
I had this one in a catch-all, #67, but it's probably worth breaking them out. For example Voyager looks dead, so I'll remove that.

Here I'm noticing a major frustration with not being able to swap the keys. I have this done in emacs and it's _much_ easier to write lisp code with these swapped.

Is it possible in Jupyter?

**Comment by yitzchak** [comment]
I don't think it is possible. Why would you not just switch the keys using a key mapper in your OS? Seems like it would very confusing to have the keys switched in a lisp text box, but not elsewhere.

**Comment by Symbolics** [comment]
Closing. The key mapper is a better solution.
