### ISSUE TITLE
How to render markdown output?

### ISSUE THREAD

**Issue by Symbolics** [yitzchak/common-lisp-jupyter#74]
I have a data structure and a function that renders it to markdown, but can't seem to get the output to display as HTML in a cell. The function is `pprint-markdown <structure>`. I have tried:
```lisp
(markdown (pprint-markdown mtcars))
(render (pprint-markdown mtcars))
```
and various combinations of switching the cell from `code` to `markdown`, but in all cases the output is rendered as text, e.g.:
```
|  | MPG | CYL | DISP | HP | DRAT | WT | QSEC | VS | AM | GEAR | CARB |
| :--- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| Mazda RX4 | 21 | 6 | 160 | 110 | 3.9d0 | 2.62d0 | 16.46d0 | 0 | 1 | 4 | 4  |
```

Can the output of a function be rendered as HTML via markdown?

**Comment by Symbolics** [comment]
I should mention that the output is going to a stream, by default `*standard-output*`. Does CLJ have a stream specifically for markdown output?

**Comment by yitzchak** [comment]
A markdown stream is being added in #72

**Comment by yitzchak** [comment]
#72 has been merged with `jupyter:*markdown-output*` as the stream name.
