### ISSUE TITLE
inline-results changed?

### ISSUE THREAD

**Issue by Symbolics** [yitzchak/common-lisp-jupyter#80]
Did something change with inline-results recently? This code previously worked:

```lisp
(defun clj-plot (spec)
  "Render a Vega-Lite specification, SPEC, in a Jupyter notebook"
  (let ((yason:*list-encoder* 'yason:encode-alist))
    (jupyter:inline-result
     (jsown:parse
      (yason:with-output-to-string* (:stream-symbol s)
	(yason:encode spec s)))
     "application/vnd.vegalite.v3+json")))
```
but now returns an error `The value "https://vega.github.io/schema/vega-lite/v5.json" is not of type LIST`, which looks a bit like a JSON processing error.

**Comment by yitzchak** [comment]
Answered over in #16
