### ISSUE TITLE
Idiomatic way to render a Vega-Lite plot?

### ISSUE THREAD

**Issue by Symbolics** [yitzchak/common-lisp-jupyter#92]
From the looks of it, the [vega-lite ](https://github.com/yitzchak/common-lisp-jupyter/blob/763147d5cb90fb408efd26422bc237aec4a382ec/src/mime-bundle.lisp#L251) function is how to tell CLJ to render a plot. However I could not find any examples of this in action.

In my use cases, I can write the Vega-Lite plot specification to strings or streams, and ideally I'd do something like:
`(vega-lite (write-spec my-plot))`. Reading [make-inline-mime-bundle](https://github.com/yitzchak/common-lisp-jupyter/blob/763147d5cb90fb408efd26422bc237aec4a382ec/src/mime-bundle.lisp#L123) makes me believe that the input needs to be a plist. I've tried to use `shasht:read-json` to convert the spec, but have experienced issues reported in yitzchak/shasht#8.

Assuming I can convince shasht to read my Vega-Lite JSON spec, it's a rather circuitous path: plist->json->plist->json and it seems 'better' if I could somehow have CLJ render the JSON spec directly.

Is this possible?

**Comment by yitzchak** [comment]
The default JSON object representation in common-lisp-jupyter are hash tables. If you do not want to pass hash tables to the `vega-lite` function you can use `:object-plist` or `:object-alist` to make one off literals. For example, `(:object-alist ("fu" . 1))` and `(:object-plist :fu 1)` are both equivalent to the JSON object `{"fu": 1}`.

Please note you do not need to create the JSON yourself. You could delay and leave it up common-lisp-jupyter to decide when that will happen. You don't even need to encode it in a `mime-bundle` subclass. All you need to implement is the method `jupyter:mime-bundle-data`. Implementing `jupyter:mime-bundle-metadata` is probably not needed for VegaLite graphs. `jupyter:mime-bundle-data` just returns an object that conforms to this https://jupyter-client.readthedocs.io/en/stable/messaging.html#display-data

```lisp
(defmethod jupyter:mime-bundle-data ((instance my-class))
  `(:object-plist "application/json" (:object-plist "a" 1)))
```

**Comment by Symbolics** [comment]
Thanks. Creating JSON isn't a problem, but creating shasht-style a/p-lists isn't something most users will be familiar with. They aren't 'true' plists, e.g. `(:object-plist "a" 1)` has an odd number of elements and most users, who define plots by hand, won't be accustom to adding `:object-plist`, especially in situations where the plot specification includes nested p-lists.

So my hope was that I could use the current tools, which do a good job of writing Vega-Lite JSON specs, to write JSON to a stream or string and render it that way. Implementing a mime-bundle-data method might be a good way to go if there aren't any streams I can get at to render the JSON directly.

**Comment by Symbolics** [comment]
I'll close with with a note that I went with the send JSON to shashat for encoding by the Vega-Lite function. It's taking the long way around, but doesn't require any more code that is already there.
