### ISSUE TITLE
read-line not prompts in loop

### ISSUE THREAD

**Issue by Schroedingersdoraemon** [yitzchak/common-lisp-jupyter#94]
Dear yitzchak,
    thanks for this common-lisp-jupyter first.

the simple code below runs differently in jupyter notebook/lab/console and sbcl directly.

```lisp
(loop (read-line *query-io*)
    (if (not (y-or-n-p "Continue?")) (return) )
)
```

When in jupyter notebook/lab/console, the (read-line) sometimes disappears and becomes the infinate loop of (y-or-n-p), but when runs in sbcl from terminal the (read-line) appears as expected.

It will be much appreciated if the reason could be found

**Comment by yitzchak** [comment]
I pushed a potent fix. Also, if you use loop clauses versus the implicit `do` variation of `loop` you can avoid the `return` and the awkward `if`.

```lisp
(loop for line = (read-line *query-io*)
      while (y-or-n-p "Continue?"))
```

**Comment by Schroedingersdoraemon** [comment]
Dear yitzchak,

thanks for your fix, now the (read-line) becomes available in the loop every time.

But, the result of (read-line) is REVERSED

If I input 123456 in (read-line), the returned value is 654321

![image](https://user-images.githubusercontent.com/43810289/173169983-6b3eaf34-f3b0-4ff6-9b22-90353509af8f.png)

**Comment by yitzchak** [comment]
Try now.

**Comment by Schroedingersdoraemon** [comment]
Dear yitzchak,

sorry for the delayed reply,

the (read-line) works exactly as expected every time,

I am a Lisp beginner and very fond of the Jupyter-style environment, thanks for your quick answers and fixes :)
